name: libdogecoin-py development
env:
  libdogecoin_url: https://github.com/dogecoinfoundation/libdogecoin.git
  libdogecoin_branch: '0.1.2-dev'
on:
  push:
    branches:
      - main
      - '*-dev'
  pull_request:
    branches:
      - main
      - '*-dev'

jobs:
  build:
    name: test on python-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      #- name: debug
      #  uses: lhotari/action-upterm@v1

      - name: compiler libdogecoin library
        run: |
          git clone --recurse-submodules --branch ${{ env.libdogecoin_branch }} ${{ env.libdogecoin_url }}
          cd libdogecoin
          sudo apt-get install -y autoconf automake libtool build-essential libevent-dev libunistring-dev
          ./autogen.sh && ./configure --prefix=build && make && make install
          cd ..
          
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          python3 -m pip install -r requirements.txt
          LIBDOGECOIN_BUILD_DIR=libdogecoin/build; python3 -m pip install .
      - name: Test with pytest
        run: |
          pytest tests
